version: 2
updates:

  # Maintain dependencies for GitHub Actions (workflows + composite actions)
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/**"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Berlin"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"
