name: Setup JDK 11
description: Setup JDK 11

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      if: env.JAVA_IS_SETUP != 'true'
      with:
        java-version: "11"
        distribution: "temurin"
        cache: maven
    - id: set_JAVA_IS_SETUP_var
      shell: bash
      run: |
        echo "JAVA_IS_SETUP=true" >> $GITHUB_ENV
