/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class Actual365Fixed extends DayCounter implements AutoCloseable {
  private transient long swigCPtr;

  protected Actual365Fixed(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.Actual365Fixed_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Actual365Fixed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Actual365Fixed obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Actual365Fixed(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public Actual365Fixed(Actual365Fixed.Convention c) {
    this(QuantLibJNI.new_Actual365Fixed__SWIG_0(c.swigValue()), true);
  }

  public Actual365Fixed() {
    this(QuantLibJNI.new_Actual365Fixed__SWIG_1(), true);
  }

  public final static class Convention {
    public final static Actual365Fixed.Convention Standard = new Actual365Fixed.Convention("Standard");
    public final static Actual365Fixed.Convention Canadian = new Actual365Fixed.Convention("Canadian");
    public final static Actual365Fixed.Convention NoLeap = new Actual365Fixed.Convention("NoLeap");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Convention swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Convention.class + " with value " + swigValue);
    }

    private Convention(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Convention(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Convention(String swigName, Convention swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Convention[] swigValues = { Standard, Canadian, NoLeap };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
