/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class CallableZeroCouponBond extends CallableBond implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CallableZeroCouponBond(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CallableZeroCouponBond_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallableZeroCouponBond obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CallableZeroCouponBond(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public CallableZeroCouponBond(int settlementDays, double faceAmount, Calendar calendar, Date maturityDate, DayCounter dayCounter, BusinessDayConvention paymentConvention, double redemption, Date issueDate, CallabilitySchedule putCallSchedule) {
    this(QuantLibJNI.new_CallableZeroCouponBond__SWIG_0(settlementDays, faceAmount, Calendar.getCPtr(calendar), calendar, Date.getCPtr(maturityDate), maturityDate, DayCounter.getCPtr(dayCounter), dayCounter, paymentConvention.swigValue(), redemption, Date.getCPtr(issueDate), issueDate, CallabilitySchedule.getCPtr(putCallSchedule), putCallSchedule), true);
  }

  public CallableZeroCouponBond(int settlementDays, double faceAmount, Calendar calendar, Date maturityDate, DayCounter dayCounter, BusinessDayConvention paymentConvention, double redemption, Date issueDate) {
    this(QuantLibJNI.new_CallableZeroCouponBond__SWIG_1(settlementDays, faceAmount, Calendar.getCPtr(calendar), calendar, Date.getCPtr(maturityDate), maturityDate, DayCounter.getCPtr(dayCounter), dayCounter, paymentConvention.swigValue(), redemption, Date.getCPtr(issueDate), issueDate), true);
  }

  public CallableZeroCouponBond(int settlementDays, double faceAmount, Calendar calendar, Date maturityDate, DayCounter dayCounter, BusinessDayConvention paymentConvention, double redemption) {
    this(QuantLibJNI.new_CallableZeroCouponBond__SWIG_2(settlementDays, faceAmount, Calendar.getCPtr(calendar), calendar, Date.getCPtr(maturityDate), maturityDate, DayCounter.getCPtr(dayCounter), dayCounter, paymentConvention.swigValue(), redemption), true);
  }

  public CallableZeroCouponBond(int settlementDays, double faceAmount, Calendar calendar, Date maturityDate, DayCounter dayCounter, BusinessDayConvention paymentConvention) {
    this(QuantLibJNI.new_CallableZeroCouponBond__SWIG_3(settlementDays, faceAmount, Calendar.getCPtr(calendar), calendar, Date.getCPtr(maturityDate), maturityDate, DayCounter.getCPtr(dayCounter), dayCounter, paymentConvention.swigValue()), true);
  }

  public CallableZeroCouponBond(int settlementDays, double faceAmount, Calendar calendar, Date maturityDate, DayCounter dayCounter) {
    this(QuantLibJNI.new_CallableZeroCouponBond__SWIG_4(settlementDays, faceAmount, Calendar.getCPtr(calendar), calendar, Date.getCPtr(maturityDate), maturityDate, DayCounter.getCPtr(dayCounter), dayCounter), true);
  }

}
