/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class CallabilitySchedule extends java.util.AbstractList<Callability> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CallabilitySchedule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallabilitySchedule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(CallabilitySchedule obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_CallabilitySchedule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
   this.delete();
  }

  public CallabilitySchedule(Callability[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Callability element : initialElements) {
      add(element);
    }
  }

  public CallabilitySchedule(Iterable<Callability> initialElements) {
    this();
    for (Callability element : initialElements) {
      add(element);
    }
  }

  public Callability get(int index) {
    return doGet(index);
  }

  public Callability set(int index, Callability e) {
    return doSet(index, e);
  }

  public boolean add(Callability e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Callability e) {
    modCount++;
    doAdd(index, e);
  }

  public Callability remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public CallabilitySchedule() {
    this(QuantLibJNI.new_CallabilitySchedule__SWIG_0(), true);
  }

  public CallabilitySchedule(CallabilitySchedule other) {
    this(QuantLibJNI.new_CallabilitySchedule__SWIG_1(CallabilitySchedule.getCPtr(other), other), true);
  }

  public long capacity() {
    return QuantLibJNI.CallabilitySchedule_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.CallabilitySchedule_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.CallabilitySchedule_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.CallabilitySchedule_clear(swigCPtr, this);
  }

  public CallabilitySchedule(int count, Callability value) {
    this(QuantLibJNI.new_CallabilitySchedule__SWIG_2(count, Callability.getCPtr(value), value), true);
  }

  private int doSize() {
    return QuantLibJNI.CallabilitySchedule_doSize(swigCPtr, this);
  }

  private void doAdd(Callability x) {
    QuantLibJNI.CallabilitySchedule_doAdd__SWIG_0(swigCPtr, this, Callability.getCPtr(x), x);
  }

  private void doAdd(int index, Callability x) {
    QuantLibJNI.CallabilitySchedule_doAdd__SWIG_1(swigCPtr, this, index, Callability.getCPtr(x), x);
  }

  private Callability doRemove(int index) {
    long cPtr = QuantLibJNI.CallabilitySchedule_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Callability(cPtr, true);
  }

  private Callability doGet(int index) {
    long cPtr = QuantLibJNI.CallabilitySchedule_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Callability(cPtr, true);
  }

  private Callability doSet(int index, Callability val) {
    long cPtr = QuantLibJNI.CallabilitySchedule_doSet(swigCPtr, this, index, Callability.getCPtr(val), val);
    return (cPtr == 0) ? null : new Callability(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    QuantLibJNI.CallabilitySchedule_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
