/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class CashFlow extends Observable implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CashFlow(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CashFlow_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CashFlow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CashFlow(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public double amount() {
    return QuantLibJNI.CashFlow_amount(swigCPtr, this);
  }

  public Date date() {
    return new Date(QuantLibJNI.CashFlow_date(swigCPtr, this), true);
  }

  public boolean hasOccurred(Date refDate) {
    return QuantLibJNI.CashFlow_hasOccurred__SWIG_0(swigCPtr, this, Date.getCPtr(refDate), refDate);
  }

  public boolean hasOccurred() {
    return QuantLibJNI.CashFlow_hasOccurred__SWIG_1(swigCPtr, this);
  }

}
