/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class ExponentialForwardCorrelation extends PiecewiseConstantCorrelation implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ExponentialForwardCorrelation(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ExponentialForwardCorrelation_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExponentialForwardCorrelation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ExponentialForwardCorrelation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public ExponentialForwardCorrelation(DoubleVector rateTimes, double longTermCorr, double beta, double gamma, DoubleVector times) {
    this(QuantLibJNI.new_ExponentialForwardCorrelation__SWIG_0(DoubleVector.getCPtr(rateTimes), rateTimes, longTermCorr, beta, gamma, DoubleVector.getCPtr(times), times), true);
  }

  public ExponentialForwardCorrelation(DoubleVector rateTimes, double longTermCorr, double beta, double gamma) {
    this(QuantLibJNI.new_ExponentialForwardCorrelation__SWIG_1(DoubleVector.getCPtr(rateTimes), rateTimes, longTermCorr, beta, gamma), true);
  }

  public ExponentialForwardCorrelation(DoubleVector rateTimes, double longTermCorr, double beta) {
    this(QuantLibJNI.new_ExponentialForwardCorrelation__SWIG_2(DoubleVector.getCPtr(rateTimes), rateTimes, longTermCorr, beta), true);
  }

  public ExponentialForwardCorrelation(DoubleVector rateTimes, double longTermCorr) {
    this(QuantLibJNI.new_ExponentialForwardCorrelation__SWIG_3(DoubleVector.getCPtr(rateTimes), rateTimes, longTermCorr), true);
  }

  public ExponentialForwardCorrelation(DoubleVector rateTimes) {
    this(QuantLibJNI.new_ExponentialForwardCorrelation__SWIG_4(DoubleVector.getCPtr(rateTimes), rateTimes), true);
  }

}
