/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class FdmHestonHullWhiteOp extends FdmLinearOpComposite implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmHestonHullWhiteOp(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmHestonHullWhiteOp_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmHestonHullWhiteOp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmHestonHullWhiteOp(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public FdmHestonHullWhiteOp(FdmMesher mesher, HestonProcess hestonProcess, HullWhiteProcess hwProcess, double equityShortRateCorrelation) {
    this(QuantLibJNI.new_FdmHestonHullWhiteOp(FdmMesher.getCPtr(mesher), mesher, HestonProcess.getCPtr(hestonProcess), hestonProcess, HullWhiteProcess.getCPtr(hwProcess), hwProcess, equityShortRateCorrelation), true);
  }

}
