/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class FdSimpleBSSwingEngine extends PricingEngine implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdSimpleBSSwingEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdSimpleBSSwingEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdSimpleBSSwingEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdSimpleBSSwingEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public FdSimpleBSSwingEngine(GeneralizedBlackScholesProcess process, long tGrid, long xGrid, FdmSchemeDesc schemeDesc) {
    this(QuantLibJNI.new_FdSimpleBSSwingEngine__SWIG_0(GeneralizedBlackScholesProcess.getCPtr(process), process, tGrid, xGrid, FdmSchemeDesc.getCPtr(schemeDesc), schemeDesc), true);
  }

  public FdSimpleBSSwingEngine(GeneralizedBlackScholesProcess process, long tGrid, long xGrid) {
    this(QuantLibJNI.new_FdSimpleBSSwingEngine__SWIG_1(GeneralizedBlackScholesProcess.getCPtr(process), process, tGrid, xGrid), true);
  }

  public FdSimpleBSSwingEngine(GeneralizedBlackScholesProcess process, long tGrid) {
    this(QuantLibJNI.new_FdSimpleBSSwingEngine__SWIG_2(GeneralizedBlackScholesProcess.getCPtr(process), process, tGrid), true);
  }

  public FdSimpleBSSwingEngine(GeneralizedBlackScholesProcess process) {
    this(QuantLibJNI.new_FdSimpleBSSwingEngine__SWIG_3(GeneralizedBlackScholesProcess.getCPtr(process), process), true);
  }

}
