/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class G2 extends ShortRateModel implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected G2(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.G2_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(G2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_G2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public G2(YieldTermStructureHandle termStructure, double a, double sigma, double b, double eta, double rho) {
    this(QuantLibJNI.new_G2__SWIG_0(YieldTermStructureHandle.getCPtr(termStructure), termStructure, a, sigma, b, eta, rho), true);
  }

  public G2(YieldTermStructureHandle termStructure, double a, double sigma, double b, double eta) {
    this(QuantLibJNI.new_G2__SWIG_1(YieldTermStructureHandle.getCPtr(termStructure), termStructure, a, sigma, b, eta), true);
  }

  public G2(YieldTermStructureHandle termStructure, double a, double sigma, double b) {
    this(QuantLibJNI.new_G2__SWIG_2(YieldTermStructureHandle.getCPtr(termStructure), termStructure, a, sigma, b), true);
  }

  public G2(YieldTermStructureHandle termStructure, double a, double sigma) {
    this(QuantLibJNI.new_G2__SWIG_3(YieldTermStructureHandle.getCPtr(termStructure), termStructure, a, sigma), true);
  }

  public G2(YieldTermStructureHandle termStructure, double a) {
    this(QuantLibJNI.new_G2__SWIG_4(YieldTermStructureHandle.getCPtr(termStructure), termStructure, a), true);
  }

  public G2(YieldTermStructureHandle termStructure) {
    this(QuantLibJNI.new_G2__SWIG_5(YieldTermStructureHandle.getCPtr(termStructure), termStructure), true);
  }

  public YieldTermStructureHandle termStructure() {
    return new YieldTermStructureHandle(QuantLibJNI.G2_termStructure(swigCPtr, this), false);
  }

}
