/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class MarkovFunctional extends Gaussian1dModel implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MarkovFunctional(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.MarkovFunctional_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarkovFunctional obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_MarkovFunctional(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public MarkovFunctional(YieldTermStructureHandle termStructure, double reversion, DateVector volstepdates, DoubleVector volatilities, SwaptionVolatilityStructureHandle swaptionVol, DateVector swaptionExpiries, PeriodVector swaptionTenors, SwapIndex swapIndexBase, MarkovFunctionalSettings modelSettings) {
    this(QuantLibJNI.new_MarkovFunctional__SWIG_0(YieldTermStructureHandle.getCPtr(termStructure), termStructure, reversion, DateVector.getCPtr(volstepdates), volstepdates, DoubleVector.getCPtr(volatilities), volatilities, SwaptionVolatilityStructureHandle.getCPtr(swaptionVol), swaptionVol, DateVector.getCPtr(swaptionExpiries), swaptionExpiries, PeriodVector.getCPtr(swaptionTenors), swaptionTenors, SwapIndex.getCPtr(swapIndexBase), swapIndexBase, MarkovFunctionalSettings.getCPtr(modelSettings), modelSettings), true);
  }

  public MarkovFunctional(YieldTermStructureHandle termStructure, double reversion, DateVector volstepdates, DoubleVector volatilities, SwaptionVolatilityStructureHandle swaptionVol, DateVector swaptionExpiries, PeriodVector swaptionTenors, SwapIndex swapIndexBase) {
    this(QuantLibJNI.new_MarkovFunctional__SWIG_1(YieldTermStructureHandle.getCPtr(termStructure), termStructure, reversion, DateVector.getCPtr(volstepdates), volstepdates, DoubleVector.getCPtr(volatilities), volatilities, SwaptionVolatilityStructureHandle.getCPtr(swaptionVol), swaptionVol, DateVector.getCPtr(swaptionExpiries), swaptionExpiries, PeriodVector.getCPtr(swaptionTenors), swaptionTenors, SwapIndex.getCPtr(swapIndexBase), swapIndexBase), true);
  }

  public MarkovFunctional(YieldTermStructureHandle termStructure, double reversion, DateVector volstepdates, DoubleVector volatilities, OptionletVolatilityStructureHandle capletVol, DateVector capletExpiries, IborIndex iborIndex, MarkovFunctionalSettings modelSettings) {
    this(QuantLibJNI.new_MarkovFunctional__SWIG_2(YieldTermStructureHandle.getCPtr(termStructure), termStructure, reversion, DateVector.getCPtr(volstepdates), volstepdates, DoubleVector.getCPtr(volatilities), volatilities, OptionletVolatilityStructureHandle.getCPtr(capletVol), capletVol, DateVector.getCPtr(capletExpiries), capletExpiries, IborIndex.getCPtr(iborIndex), iborIndex, MarkovFunctionalSettings.getCPtr(modelSettings), modelSettings), true);
  }

  public MarkovFunctional(YieldTermStructureHandle termStructure, double reversion, DateVector volstepdates, DoubleVector volatilities, OptionletVolatilityStructureHandle capletVol, DateVector capletExpiries, IborIndex iborIndex) {
    this(QuantLibJNI.new_MarkovFunctional__SWIG_3(YieldTermStructureHandle.getCPtr(termStructure), termStructure, reversion, DateVector.getCPtr(volstepdates), volstepdates, DoubleVector.getCPtr(volatilities), volatilities, OptionletVolatilityStructureHandle.getCPtr(capletVol), capletVol, DateVector.getCPtr(capletExpiries), capletExpiries, IborIndex.getCPtr(iborIndex), iborIndex), true);
  }

  public Array volatility() {
    return new Array(QuantLibJNI.MarkovFunctional_volatility(swigCPtr, this), false);
  }

  public void calibrate(CalibrationHelperVector helper, OptimizationMethod method, EndCriteria endCriteria, Constraint constraint, DoubleVector weights, BoolVector fixParameters) {
    QuantLibJNI.MarkovFunctional_calibrate__SWIG_0(swigCPtr, this, CalibrationHelperVector.getCPtr(helper), helper, OptimizationMethod.getCPtr(method), method, EndCriteria.getCPtr(endCriteria), endCriteria, Constraint.getCPtr(constraint), constraint, DoubleVector.getCPtr(weights), weights, BoolVector.getCPtr(fixParameters), fixParameters);
  }

  public void calibrate(CalibrationHelperVector helper, OptimizationMethod method, EndCriteria endCriteria, Constraint constraint, DoubleVector weights) {
    QuantLibJNI.MarkovFunctional_calibrate__SWIG_1(swigCPtr, this, CalibrationHelperVector.getCPtr(helper), helper, OptimizationMethod.getCPtr(method), method, EndCriteria.getCPtr(endCriteria), endCriteria, Constraint.getCPtr(constraint), constraint, DoubleVector.getCPtr(weights), weights);
  }

  public void calibrate(CalibrationHelperVector helper, OptimizationMethod method, EndCriteria endCriteria, Constraint constraint) {
    QuantLibJNI.MarkovFunctional_calibrate__SWIG_2(swigCPtr, this, CalibrationHelperVector.getCPtr(helper), helper, OptimizationMethod.getCPtr(method), method, EndCriteria.getCPtr(endCriteria), endCriteria, Constraint.getCPtr(constraint), constraint);
  }

  public void calibrate(CalibrationHelperVector helper, OptimizationMethod method, EndCriteria endCriteria) {
    QuantLibJNI.MarkovFunctional_calibrate__SWIG_3(swigCPtr, this, CalibrationHelperVector.getCPtr(helper), helper, OptimizationMethod.getCPtr(method), method, EndCriteria.getCPtr(endCriteria), endCriteria);
  }

  public Array params() {
    return new Array(QuantLibJNI.MarkovFunctional_params(swigCPtr, this), true);
  }

  public void setParams(Array params) {
    QuantLibJNI.MarkovFunctional_setParams(swigCPtr, this, Array.getCPtr(params), params);
  }

  public double value(Array params, CalibrationHelperVector instruments) {
    return QuantLibJNI.MarkovFunctional_value(swigCPtr, this, Array.getCPtr(params), params, CalibrationHelperVector.getCPtr(instruments), instruments);
  }

  public Constraint constraint() {
    long cPtr = QuantLibJNI.MarkovFunctional_constraint(swigCPtr, this);
    return (cPtr == 0) ? null : new Constraint(cPtr, true);
  }

  public EndCriteria.Type endCriteria() {
    return EndCriteria.Type.swigToEnum(QuantLibJNI.MarkovFunctional_endCriteria(swigCPtr, this));
  }

  public Array problemValues() {
    return new Array(QuantLibJNI.MarkovFunctional_problemValues(swigCPtr, this), false);
  }

  public int functionEvaluation() {
    return QuantLibJNI.MarkovFunctional_functionEvaluation(swigCPtr, this);
  }

}
