/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class NodeVector extends java.util.AbstractList<NodePair> implements AutoCloseable, java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(NodeVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_NodeVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
   this.delete();
  }

  public NodeVector(NodePair[] initialElements) {
    this();
    reserve(initialElements.length);

    for (NodePair element : initialElements) {
      add(element);
    }
  }

  public NodeVector(Iterable<NodePair> initialElements) {
    this();
    for (NodePair element : initialElements) {
      add(element);
    }
  }

  public NodePair get(int index) {
    return doGet(index);
  }

  public NodePair set(int index, NodePair e) {
    return doSet(index, e);
  }

  public boolean add(NodePair e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, NodePair e) {
    modCount++;
    doAdd(index, e);
  }

  public NodePair remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public NodeVector() {
    this(QuantLibJNI.new_NodeVector__SWIG_0(), true);
  }

  public NodeVector(NodeVector other) {
    this(QuantLibJNI.new_NodeVector__SWIG_1(NodeVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return QuantLibJNI.NodeVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    QuantLibJNI.NodeVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return QuantLibJNI.NodeVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    QuantLibJNI.NodeVector_clear(swigCPtr, this);
  }

  public NodeVector(int count, NodePair value) {
    this(QuantLibJNI.new_NodeVector__SWIG_2(count, NodePair.getCPtr(value), value), true);
  }

  private int doSize() {
    return QuantLibJNI.NodeVector_doSize(swigCPtr, this);
  }

  private void doAdd(NodePair x) {
    QuantLibJNI.NodeVector_doAdd__SWIG_0(swigCPtr, this, NodePair.getCPtr(x), x);
  }

  private void doAdd(int index, NodePair x) {
    QuantLibJNI.NodeVector_doAdd__SWIG_1(swigCPtr, this, index, NodePair.getCPtr(x), x);
  }

  private NodePair doRemove(int index) {
    return new NodePair(QuantLibJNI.NodeVector_doRemove(swigCPtr, this, index), true);
  }

  private NodePair doGet(int index) {
    return new NodePair(QuantLibJNI.NodeVector_doGet(swigCPtr, this, index), false);
  }

  private NodePair doSet(int index, NodePair val) {
    return new NodePair(QuantLibJNI.NodeVector_doSet(swigCPtr, this, index, NodePair.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    QuantLibJNI.NodeVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
