/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class RelinkableDefaultProbabilityTermStructureHandle extends DefaultProbabilityTermStructureHandle implements AutoCloseable {
  private transient long swigCPtr;

  protected RelinkableDefaultProbabilityTermStructureHandle(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.RelinkableDefaultProbabilityTermStructureHandle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RelinkableDefaultProbabilityTermStructureHandle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RelinkableDefaultProbabilityTermStructureHandle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_RelinkableDefaultProbabilityTermStructureHandle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public RelinkableDefaultProbabilityTermStructureHandle(DefaultProbabilityTermStructure arg0) {
    this(QuantLibJNI.new_RelinkableDefaultProbabilityTermStructureHandle__SWIG_0(DefaultProbabilityTermStructure.getCPtr(arg0), arg0), true);
  }

  public RelinkableDefaultProbabilityTermStructureHandle() {
    this(QuantLibJNI.new_RelinkableDefaultProbabilityTermStructureHandle__SWIG_1(), true);
  }

  public void linkTo(DefaultProbabilityTermStructure arg0) {
    QuantLibJNI.RelinkableDefaultProbabilityTermStructureHandle_linkTo(swigCPtr, this, DefaultProbabilityTermStructure.getCPtr(arg0), arg0);
  }

  public void reset() {
    QuantLibJNI.RelinkableDefaultProbabilityTermStructureHandle_reset(swigCPtr, this);
  }

}
