/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class UnaryFunctionDelegate implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnaryFunctionDelegate(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnaryFunctionDelegate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(UnaryFunctionDelegate obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_UnaryFunctionDelegate(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    QuantLibJNI.UnaryFunctionDelegate_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    QuantLibJNI.UnaryFunctionDelegate_change_ownership(this, swigCPtr, true);
  }

  @Override
  public void close() {
   this.delete();
  }

  public double value(double x) {
    return (getClass() == UnaryFunctionDelegate.class) ? QuantLibJNI.UnaryFunctionDelegate_value(swigCPtr, this, x) : QuantLibJNI.UnaryFunctionDelegate_valueSwigExplicitUnaryFunctionDelegate(swigCPtr, this, x);
  }

  public UnaryFunctionDelegate() {
    this(QuantLibJNI.new_UnaryFunctionDelegate(), true);
    QuantLibJNI.UnaryFunctionDelegate_director_connect(this, swigCPtr, true, true);
  }

}
