/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class VannaVolgaBarrierEngine extends PricingEngine implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected VannaVolgaBarrierEngine(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.VannaVolgaBarrierEngine_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VannaVolgaBarrierEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_VannaVolgaBarrierEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public VannaVolgaBarrierEngine(DeltaVolQuoteHandle atmVol, DeltaVolQuoteHandle vol25Put, DeltaVolQuoteHandle vol25Call, QuoteHandle spotFX, YieldTermStructureHandle domesticTS, YieldTermStructureHandle foreignTS, boolean adaptVanDelta, double bsPriceWithSmile) {
    this(QuantLibJNI.new_VannaVolgaBarrierEngine__SWIG_0(DeltaVolQuoteHandle.getCPtr(atmVol), atmVol, DeltaVolQuoteHandle.getCPtr(vol25Put), vol25Put, DeltaVolQuoteHandle.getCPtr(vol25Call), vol25Call, QuoteHandle.getCPtr(spotFX), spotFX, YieldTermStructureHandle.getCPtr(domesticTS), domesticTS, YieldTermStructureHandle.getCPtr(foreignTS), foreignTS, adaptVanDelta, bsPriceWithSmile), true);
  }

  public VannaVolgaBarrierEngine(DeltaVolQuoteHandle atmVol, DeltaVolQuoteHandle vol25Put, DeltaVolQuoteHandle vol25Call, QuoteHandle spotFX, YieldTermStructureHandle domesticTS, YieldTermStructureHandle foreignTS, boolean adaptVanDelta) {
    this(QuantLibJNI.new_VannaVolgaBarrierEngine__SWIG_1(DeltaVolQuoteHandle.getCPtr(atmVol), atmVol, DeltaVolQuoteHandle.getCPtr(vol25Put), vol25Put, DeltaVolQuoteHandle.getCPtr(vol25Call), vol25Call, QuoteHandle.getCPtr(spotFX), spotFX, YieldTermStructureHandle.getCPtr(domesticTS), domesticTS, YieldTermStructureHandle.getCPtr(foreignTS), foreignTS, adaptVanDelta), true);
  }

  public VannaVolgaBarrierEngine(DeltaVolQuoteHandle atmVol, DeltaVolQuoteHandle vol25Put, DeltaVolQuoteHandle vol25Call, QuoteHandle spotFX, YieldTermStructureHandle domesticTS, YieldTermStructureHandle foreignTS) {
    this(QuantLibJNI.new_VannaVolgaBarrierEngine__SWIG_2(DeltaVolQuoteHandle.getCPtr(atmVol), atmVol, DeltaVolQuoteHandle.getCPtr(vol25Put), vol25Put, DeltaVolQuoteHandle.getCPtr(vol25Call), vol25Call, QuoteHandle.getCPtr(spotFX), spotFX, YieldTermStructureHandle.getCPtr(domesticTS), domesticTS, YieldTermStructureHandle.getCPtr(foreignTS), foreignTS), true);
  }

}
