/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class YoYInflationIndex extends InflationIndex implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected YoYInflationIndex(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.YoYInflationIndex_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YoYInflationIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_YoYInflationIndex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public YoYInflationIndex(String familyName, Region region, boolean revised, boolean interpolated, boolean ratio, Frequency frequency, Period availabilityLag, Currency currency, YoYInflationTermStructureHandle ts) {
    this(QuantLibJNI.new_YoYInflationIndex__SWIG_0(familyName, Region.getCPtr(region), region, revised, interpolated, ratio, frequency.swigValue(), Period.getCPtr(availabilityLag), availabilityLag, Currency.getCPtr(currency), currency, YoYInflationTermStructureHandle.getCPtr(ts), ts), true);
  }

  public YoYInflationIndex(String familyName, Region region, boolean revised, boolean interpolated, boolean ratio, Frequency frequency, Period availabilityLag, Currency currency) {
    this(QuantLibJNI.new_YoYInflationIndex__SWIG_1(familyName, Region.getCPtr(region), region, revised, interpolated, ratio, frequency.swigValue(), Period.getCPtr(availabilityLag), availabilityLag, Currency.getCPtr(currency), currency), true);
  }

  public boolean ratio() {
    return QuantLibJNI.YoYInflationIndex_ratio(swigCPtr, this);
  }

  public YoYInflationTermStructureHandle yoyInflationTermStructure() {
    return new YoYInflationTermStructureHandle(QuantLibJNI.YoYInflationIndex_yoyInflationTermStructure(swigCPtr, this), true);
  }

  public YoYInflationIndex clone(YoYInflationTermStructureHandle h) {
    long cPtr = QuantLibJNI.YoYInflationIndex_clone(swigCPtr, this, YoYInflationTermStructureHandle.getCPtr(h), h);
    return (cPtr == 0) ? null : new YoYInflationIndex(cPtr, true);
  }

}
