/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class ZabrShortMaturityLognormalSmileSection extends SmileSection implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ZabrShortMaturityLognormalSmileSection(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.ZabrShortMaturityLognormalSmileSection_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZabrShortMaturityLognormalSmileSection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_ZabrShortMaturityLognormalSmileSection(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public ZabrShortMaturityLognormalSmileSection(double timeToExpiry, double forward, DoubleVector zabrParameters, DoubleVector moneyness, long fdRefinement) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_0(timeToExpiry, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters, DoubleVector.getCPtr(moneyness), moneyness, fdRefinement), true);
  }

  public ZabrShortMaturityLognormalSmileSection(double timeToExpiry, double forward, DoubleVector zabrParameters, DoubleVector moneyness) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_1(timeToExpiry, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters, DoubleVector.getCPtr(moneyness), moneyness), true);
  }

  public ZabrShortMaturityLognormalSmileSection(double timeToExpiry, double forward, DoubleVector zabrParameters) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_2(timeToExpiry, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters), true);
  }

  public ZabrShortMaturityLognormalSmileSection(Date d, double forward, DoubleVector zabrParameters, DayCounter dc, DoubleVector moneyness, long fdRefinement) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_3(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters, DayCounter.getCPtr(dc), dc, DoubleVector.getCPtr(moneyness), moneyness, fdRefinement), true);
  }

  public ZabrShortMaturityLognormalSmileSection(Date d, double forward, DoubleVector zabrParameters, DayCounter dc, DoubleVector moneyness) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_4(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters, DayCounter.getCPtr(dc), dc, DoubleVector.getCPtr(moneyness), moneyness), true);
  }

  public ZabrShortMaturityLognormalSmileSection(Date d, double forward, DoubleVector zabrParameters, DayCounter dc) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_5(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters, DayCounter.getCPtr(dc), dc), true);
  }

  public ZabrShortMaturityLognormalSmileSection(Date d, double forward, DoubleVector zabrParameters) {
    this(QuantLibJNI.new_ZabrShortMaturityLognormalSmileSection__SWIG_6(Date.getCPtr(d), d, forward, DoubleVector.getCPtr(zabrParameters), zabrParameters), true);
  }

}
