name: Setup of the needed software
description: Setup of the needed software

inputs:
  runner-name:
    description: The runner name to be used for ccache key name
    default: ''
    required: true
  java-version:
    description: The java jdk version to setup
    default: ''
    required: true
  gpg-secret-key:
    description: The gpg secret key
    default: ''
    required: true

runs:
  using: composite
  steps:
    - name: Check if runner-name variable is Set
      if: inputs.runner-name == ''
      shell: bash
      run: |
        echo "The variable 'runner-name' was not set"  
        exit 1

    - name: Setup Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache ninja-build
        sudo apt-get remove -y swig swig4.0
        
        brew update
        brew install swig boost

    - name: Setup macOs
      if: runner.os == 'macOs'
      shell: bash
      run: |
        brew update
        brew install ninja boost

    - name: Setup macOs 13 and macOs 14
      if: inputs.runner-name == 'macos-13' || inputs.runner-name == 'macos-14'
      shell: bash
      run: |
        brew install swig

    - name: Setup Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Start-BitsTransfer -Source $env:BOOST_DOWNLOAD_URI -Destination $env:BOOST_INSTALLER_PATH
        Start-Process -Wait -FilePath "$env:BOOST_INSTALLER_PATH" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$env:BOOST_ROOT"
        
        Start-BitsTransfer -Source $env:SWIG_DOWNLOAD_URI -Destination $env:SWIG_ZIP_FILE_PATH
        Expand-Archive $env:SWIG_ZIP_FILE_PATH $env:RUNNER_TEMP
        swig -version

        choco install -y ninja

    - name: Set up JDK ${{ inputs.java-version }}
      uses: ./.github/actions/build_native_library/setup/jdk
      with:
        java-version:   ${{ inputs.java-version }}
        gpg-secret-key: ${{ inputs.gpg-secret-key }}

    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: ${{ env.CMAKE_CXX_COMPILER_LAUNCHER }}
        key: ${{ runner.os }}--${{ inputs.runner-name }}--${{ github.job }}
        restore-keys: |
          ${{ runner.os }}--${{ inputs.runner-name }}--${{ github.job }}
          ${{ runner.os }}--${{ inputs.runner-name }}
          ${{ runner.os }}

    - name: Set up Visual Studio shell on Windows
      uses: TheMrMilchmann/setup-msvc-dev@v3
      if: runner.os == 'Windows'
      with:
        arch: x64
