/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class Calendar implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Calendar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Calendar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Calendar obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        QuantLibJNI.delete_Calendar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void close() {
   this.delete();
  }

  public boolean isWeekend(Weekday w) {
    return QuantLibJNI.Calendar_isWeekend(swigCPtr, this, w.swigValue());
  }

  public Date endOfMonth(Date arg0) {
    return new Date(QuantLibJNI.Calendar_endOfMonth(swigCPtr, this, Date.getCPtr(arg0), arg0), true);
  }

  public boolean isBusinessDay(Date arg0) {
    return QuantLibJNI.Calendar_isBusinessDay(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public boolean isHoliday(Date arg0) {
    return QuantLibJNI.Calendar_isHoliday(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public boolean isEndOfMonth(Date arg0) {
    return QuantLibJNI.Calendar_isEndOfMonth(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public void addHoliday(Date arg0) {
    QuantLibJNI.Calendar_addHoliday(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public void removeHoliday(Date arg0) {
    QuantLibJNI.Calendar_removeHoliday(swigCPtr, this, Date.getCPtr(arg0), arg0);
  }

  public Date adjust(Date d, BusinessDayConvention convention) {
    return new Date(QuantLibJNI.Calendar_adjust__SWIG_0(swigCPtr, this, Date.getCPtr(d), d, convention.swigValue()), true);
  }

  public Date adjust(Date d) {
    return new Date(QuantLibJNI.Calendar_adjust__SWIG_1(swigCPtr, this, Date.getCPtr(d), d), true);
  }

  public Date advance(Date d, int n, TimeUnit unit, BusinessDayConvention convention, boolean endOfMonth) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_0(swigCPtr, this, Date.getCPtr(d), d, n, unit.swigValue(), convention.swigValue(), endOfMonth), true);
  }

  public Date advance(Date d, int n, TimeUnit unit, BusinessDayConvention convention) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_1(swigCPtr, this, Date.getCPtr(d), d, n, unit.swigValue(), convention.swigValue()), true);
  }

  public Date advance(Date d, int n, TimeUnit unit) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_2(swigCPtr, this, Date.getCPtr(d), d, n, unit.swigValue()), true);
  }

  public Date advance(Date d, Period period, BusinessDayConvention convention, boolean endOfMonth) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_3(swigCPtr, this, Date.getCPtr(d), d, Period.getCPtr(period), period, convention.swigValue(), endOfMonth), true);
  }

  public Date advance(Date d, Period period, BusinessDayConvention convention) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_4(swigCPtr, this, Date.getCPtr(d), d, Period.getCPtr(period), period, convention.swigValue()), true);
  }

  public Date advance(Date d, Period period) {
    return new Date(QuantLibJNI.Calendar_advance__SWIG_5(swigCPtr, this, Date.getCPtr(d), d, Period.getCPtr(period), period), true);
  }

  public int businessDaysBetween(Date from, Date to, boolean includeFirst, boolean includeLast) {
    return QuantLibJNI.Calendar_businessDaysBetween__SWIG_0(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to, includeFirst, includeLast);
  }

  public int businessDaysBetween(Date from, Date to, boolean includeFirst) {
    return QuantLibJNI.Calendar_businessDaysBetween__SWIG_1(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to, includeFirst);
  }

  public int businessDaysBetween(Date from, Date to) {
    return QuantLibJNI.Calendar_businessDaysBetween__SWIG_2(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to);
  }

  public DateVector holidayList(Date from, Date to, boolean includeWeekEnds) {
    return new DateVector(QuantLibJNI.Calendar_holidayList__SWIG_0(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to, includeWeekEnds), true);
  }

  public DateVector holidayList(Date from, Date to) {
    return new DateVector(QuantLibJNI.Calendar_holidayList__SWIG_1(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to), true);
  }

  public DateVector businessDayList(Date from, Date to) {
    return new DateVector(QuantLibJNI.Calendar_businessDayList(swigCPtr, this, Date.getCPtr(from), from, Date.getCPtr(to), to), true);
  }

  public String name() {
    return QuantLibJNI.Calendar_name(swigCPtr, this);
  }

  public String toString() {
    return QuantLibJNI.Calendar_toString(swigCPtr, this);
  }

  public boolean equals(Calendar other) {
    return QuantLibJNI.Calendar_equals(swigCPtr, this, Calendar.getCPtr(other), other);
  }

  public boolean unEquals(Calendar other) {
    return QuantLibJNI.Calendar_unEquals(swigCPtr, this, Calendar.getCPtr(other), other);
  }

}
