/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class CompositeInstrument extends Instrument implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CompositeInstrument(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.CompositeInstrument_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompositeInstrument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_CompositeInstrument(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public CompositeInstrument() {
    this(QuantLibJNI.new_CompositeInstrument(), true);
  }

  public void add(Instrument instrument, double multiplier) {
    QuantLibJNI.CompositeInstrument_add__SWIG_0(swigCPtr, this, Instrument.getCPtr(instrument), instrument, multiplier);
  }

  public void add(Instrument instrument) {
    QuantLibJNI.CompositeInstrument_add__SWIG_1(swigCPtr, this, Instrument.getCPtr(instrument), instrument);
  }

  public void subtract(Instrument instrument, double multiplier) {
    QuantLibJNI.CompositeInstrument_subtract__SWIG_0(swigCPtr, this, Instrument.getCPtr(instrument), instrument, multiplier);
  }

  public void subtract(Instrument instrument) {
    QuantLibJNI.CompositeInstrument_subtract__SWIG_1(swigCPtr, this, Instrument.getCPtr(instrument), instrument);
  }

}
