/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class FdmTimeDepDirichletBoundary extends FdmBoundaryCondition implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FdmTimeDepDirichletBoundary(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FdmTimeDepDirichletBoundary_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FdmTimeDepDirichletBoundary obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FdmTimeDepDirichletBoundary(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public FdmTimeDepDirichletBoundary(FdmMesher mesher, UnaryFunctionDelegate function, long direction, FdmBoundaryCondition.Side side) {
    this(QuantLibJNI.new_FdmTimeDepDirichletBoundary(FdmMesher.getCPtr(mesher), mesher, UnaryFunctionDelegate.getCPtr(function), function, direction, side.swigValue()), true);
  }

}
