/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class FxSwapRateHelper extends RateHelper implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected FxSwapRateHelper(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.FxSwapRateHelper_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FxSwapRateHelper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_FxSwapRateHelper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public FxSwapRateHelper(QuoteHandle fwdPoint, QuoteHandle spotFx, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, boolean isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle collateralCurve, Calendar tradingCalendar) {
    this(QuantLibJNI.new_FxSwapRateHelper__SWIG_0(QuoteHandle.getCPtr(fwdPoint), fwdPoint, QuoteHandle.getCPtr(spotFx), spotFx, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve, Calendar.getCPtr(tradingCalendar), tradingCalendar), true);
  }

  public FxSwapRateHelper(QuoteHandle fwdPoint, QuoteHandle spotFx, Period tenor, long fixingDays, Calendar calendar, BusinessDayConvention convention, boolean endOfMonth, boolean isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle collateralCurve) {
    this(QuantLibJNI.new_FxSwapRateHelper__SWIG_1(QuoteHandle.getCPtr(fwdPoint), fwdPoint, QuoteHandle.getCPtr(spotFx), spotFx, Period.getCPtr(tenor), tenor, fixingDays, Calendar.getCPtr(calendar), calendar, convention.swigValue(), endOfMonth, isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle.getCPtr(collateralCurve), collateralCurve), true);
  }

}
