/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.quantlib;

import java.lang.AutoCloseable;

public class SwaptionVolatilityDiscrete extends SwaptionVolatilityStructure implements AutoCloseable {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected SwaptionVolatilityDiscrete(long cPtr, boolean cMemoryOwn) {
    super(QuantLibJNI.SwaptionVolatilityDiscrete_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SwaptionVolatilityDiscrete obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        QuantLibJNI.delete_SwaptionVolatilityDiscrete(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  @Override
  public void close() {
   this.delete();
  }

  public PeriodVector optionTenors() {
    return new PeriodVector(QuantLibJNI.SwaptionVolatilityDiscrete_optionTenors(swigCPtr, this), false);
  }

  public DateVector optionDates() {
    return new DateVector(QuantLibJNI.SwaptionVolatilityDiscrete_optionDates(swigCPtr, this), false);
  }

  public DoubleVector optionTimes() {
    return new DoubleVector(QuantLibJNI.SwaptionVolatilityDiscrete_optionTimes(swigCPtr, this), false);
  }

  public PeriodVector swapTenors() {
    return new PeriodVector(QuantLibJNI.SwaptionVolatilityDiscrete_swapTenors(swigCPtr, this), false);
  }

  public DoubleVector swapLengths() {
    return new DoubleVector(QuantLibJNI.SwaptionVolatilityDiscrete_swapLengths(swigCPtr, this), false);
  }

  public Date optionDateFromTime(double optionTime) {
    return new Date(QuantLibJNI.SwaptionVolatilityDiscrete_optionDateFromTime(swigCPtr, this, optionTime), true);
  }

}
