name: Setup needed environment variables
description: Setup needed environment variables

inputs:
  gpg-secret-key-password:
    description: The password for the gpg secret key
    default: ''
    required: true

runs:
  using: composite
  steps:
    - name: Set the 'MAVEN_GPG_PASSPHRASE'
      shell: bash
      run: |
        echo "MAVEN_GPG_PASSPHRASE=${{ inputs.gpg-secret-key-password }}"                                                               >> $GITHUB_ENV

    - name: Determine ccache variant
      shell: bash
      run: |
        echo "CMAKE_CXX_COMPILER_LAUNCHER=${{ ( (runner.os == 'Windows') && 'sccache' ) || 'ccache' }}"                                 >> $GITHUB_ENV

    - name: Setup Homebrew on Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin"                                                           >> $GITHUB_PATH

    - name: Setup build variables on macOs
      if: runner.os == 'macOs'
      shell: bash
      run: |
        echo "CXXFLAGS=-stdlib=libc++"                                                                                                  >> $GITHUB_ENV
        echo "HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1"                                                                                 >> $GITHUB_ENV

    - name: Setup BOOST_ROOT and directories on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Write "BOOST_DOWNLOAD_URI=https://downloads.sourceforge.net/project/boost/boost-binaries/1.86.0/boost_1_86_0-msvc-14.3-64.exe"  >> $env:GITHUB_ENV
        Write "BOOST_INSTALLER_PATH=$env:RUNNER_TEMP\boost.exe"                                                                         >> $env:GITHUB_ENV
        Write "BOOST_ROOT=$env:RUNNER_TEMP\boost"                                                                                       >> $env:GITHUB_ENV

        Write "SWIG_DOWNLOAD_URI=https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.1/swigwin-4.2.1.zip/download"          >> $env:GITHUB_ENV
        Write "SWIG_ZIP_FILE_PATH=$env:RUNNER_TEMP\swigwin-4.2.1.zip"                                                                   >> $env:GITHUB_ENV
        Write "$env:RUNNER_TEMP\swigwin-4.2.1"                                                                                          >> $env:GITHUB_PATH
