name: Build native library for the runner
description: Build native library for the runner

inputs:
  runner-name:
    description: The runner name to be used for ccache key name
    default: ''
    required: true
  gpg-secret-key:
    description: The gpg secret key
    default: ''
    required: true
  gpg-secret-key-password:
    description: The password for the gpg secret key
    default: ''
    required: true
  upload-path:
    description: The path where to find the native library to upload
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: ./.github/actions/build_native_library/env_variables

    - uses: ./.github/actions/build_native_library/setup
      with:
        runner-name: ${{ inputs.runner-name }}
        gpg-secret-key: ${{ inputs.gpg-secret-key }}

    - name: Build
      shell: bash
      env:
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-secret-key-password }}
      run: |
        cmake --version
        cmake --preset release -L
        cmake --build --preset release --verbose

    - name: Upload native library
      if: ${{ inputs.upload-path != '' }}
      uses: actions/upload-artifact@v3
      with:
        name: native-library-${{ runner.os }}
        path: ${{ inputs.upload-path }}
        retention-days: 1
